### ISSUE TITLE
Please add screenshots

### ISSUE THREAD

**Issue by jezmck** [material-theme/gitkraken#1]
Please add screenshots for each theme to the readme.

**Comment by equinusocio** [comment]
For now you can use these as reference

![FIHJAmTX0AkAFeM](https://user-images.githubusercontent.com/10454741/153393054-d5196138-dec7-4f54-b4b2-b39b8da63eb7.jpg)
![FIHJAmWXoAEk4R-](https://user-images.githubusercontent.com/10454741/153393062-bc34694d-1d50-4a5d-9735-9362be79a12d.jpg)
![FIHJAmVX0AwZBcx](https://user-images.githubusercontent.com/10454741/153393047-f2ca790d-70f3-4bd2-9962-a3424553210d.jpg)
![FIHJAmZXEAIUPuB](https://user-images.githubusercontent.com/10454741/153393039-4f15be0d-2b06-4fc9-ad13-c005d7787885.jpg)
